### ISSUE TITLE
Hook updates in install file

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#1]
Nice job on getting webform migrated!

I haven't tried it yet, but noticed that there should be a 1xxx update function from Drupal to Backdrop. And can drop the 7xxx updates.

I look forward to giving it a spin.

**Comment by biolithic** [comment]
Yes, I was running out of time getting the 1xxx updates in there, so
decided to just upload anyway and put them in at a later day (probably
today)

**Comment by docwilmot** [comment]
Also should remove the variable_dels from uninstall, and remove the config_sets from install.
It might be good also to add a note in the README about why this conditional 
`if (config_get('webform.settings', 'webform_install_create_content_type')) {` 
exists. [here is why](https://www.drupal.org/node/1263584)
