### ISSUE TITLE
Error when configuring Webform block's View mode as Full content

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/webform#10]
I try to configure Webform block.
If I select View mode > Full content then I get the error and the block View mode is saved as Form only.

![webform_1](https://cloud.githubusercontent.com/assets/13515302/9607396/953f8f56-50d1-11e5-8f4d-8d3e6559b197.gif)

![webform_2](https://cloud.githubusercontent.com/assets/13515302/9607399/9ade4588-50d1-11e5-9b8a-23543c6871f6.gif)

**Comment by herbdool** [comment]
This appears to be working now.

There have been a bunch of small fixes, one of which might have addressed this.
