### ISSUE TITLE
Email Tokens Not Replaced

### ISSUE THREAD

**Issue by bobchristenson** [backdrop-contrib/webform#105]
I have a stock install of webform with no modifications.  When I create a webform and set it up to send an email everything works fine (submission, email sending, etc).  I leave the email as 100% default message.

When the email arrives, no tokens have been replaced.  

Are there additional modules I'm missing?  Advice on troubleshooting?

**Comment by jenlampton** [comment]
> no tokens have been replaced.

Are the tokens you're using Backdrop core's tokens, or the old webform-style tokens from webform 3.x? Can you post an example of some of the tokens here?

**Comment by bobchristenson** [comment]
That's why I mentioned that I just used whatever was default in the form (I didn't change anything)..I figured those defaults should work.  Now that you say it that way, I'm thinking maybe the defaults weren't changed when the module was ported from Drupal and those tokens don't exist (yet) in Backdrop?

**Comment by jenlampton** [comment]
Drupal went the other way, all the Webform tokens were replaced with "official" tokens and an upgrade path was provided instead. It seems that if the tokens are still in the webform default, webform would also (still) be providing the token replacements...  let me see... can you see any of the tokens in your email in [here](https://github.com/backdrop-contrib/webform/blob/1.x-1.x/webform.tokens.inc)?

**Comment by herbdool** [comment]
Backdrop's Webform is pretty much the same as Drupal 7's Webform. I tested this out just now.

I can include global tokens and they do get filled in, such as the webform's node url, the site name, etc. *And* I can also include the submission values. **But** you need to check off all the values that you want included. This should probably be all by default, but it does work once you select the values in the **Included Email Values** under the **Email Template** (something like `/node/*/webform/emails/*`

**Comment by bobchristenson** [comment]
My webform has all the 'submission' tokens..but they're not being replaced (and you can't select those to activate them). I have all the ones active you can select.  Here's the email that's not being replaced (ie. the default)...shouldn't these always work?:
`Submitted on [submission:date:long]
Submitted by user: [submission:user]
Submitted values are:
[submission:values]

The results of this submission may be viewed at:
[submission:url]`

**Comment by herbdool** [comment]
Maybe you could include some screenshots @bobchristenson just to confirm we're on the same page? I can't replicate the issue. I just tested again on my local fresh install. When I use the default template I get:

```
Submitted on Wednesday, May 23, 2018 - 5:24pm
Submitted by user: admin
Submitted values are:

Size: Large
Day of the week: Tuesday


The results of this submission may be viewed at:
http://backdrop.lndo.site/node/12/submission/6
```

When I customize a different webform's template and include component individually plus some general tokens, they all get replaced:

```
Submitted on Wednesday, May 23, 2018 - 5:19pm
Submitted by user: admin
Submitted values are:

Name: Red
Favourite colour: Green


The results of this submission may be viewed at:
http://backdrop.lndo.site/node/9/submission/55

Login: http://backdrop.lndo.site/user

Note title: my first webform
Node link: http://backdrop.lndo.site/webform/my-first-webform

Individual components:
Red
Green
```

**Comment by bobchristenson** [comment]
Yeah, I need to dig into this deeper because as of now, I still don't have any tokens being replaced.  Right now my email body looks like this when I get it:
`
Submitted on [submission:date:long]
Submitted by anonymous user: [submission:ip-address]
Submitted values are:
[submission:values]

The results of this submission may be viewed at:
[submission:url]
`

**Comment by herbdool** [comment]
I'm going to close this issue. If you still see an issue please open a new issue.

**Comment by yorkshire-pudding** [comment]
@bobchristenson - I assume you've got this working by now, but for the record and anyone else coming across this.
I had the same issue but went to `admin/config/content/webform` (Configuration > Content authoring > Webform settings)

Scroll down to Advanced options > Token access and select "Allow tokens to be used in Webforms."

![image](https://user-images.githubusercontent.com/20357797/222899875-46a33eac-6a21-43e3-9204-1e87d02b526e.png)

FYI @herbdool @jenlampton

**Comment by bobchristenson** [comment]
Actually I never did solve this..it was my own site so i just gave up on it!  I think when i installed this site originally (almost 5 years ago!) this setting probably defaulted to 'no tokens'.  But I bet that changed because I've never had this problem on a client site.

Thanks, I FINALLY fixed this after all these years :)
