### ISSUE TITLE
Error After Upgrade from Drupal 7

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-contrib/webform#108]
After Upgrading site from Drupal 7 the following error prevents existing webform nodes from displaying:

` Notice: Undefined index: preview_excluded_components in webform_node_load() (line 1744 of /modules/webform/webform.module).
    PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'webform_roles.role' in 'field list': SELECT webform_roles.role AS role FROM {webform_roles} webform_roles WHERE (nid = :db_condition_placeholder_0) ; Array ( [:db_condition_placeholder_0] => 39 ) in webform_node_load() (line 1764 of /modules/webform/webform.module).`

**Comment by herbdool** [comment]
Hi @larsdesigns what version of webform on Drupal 7 were you using and which version on webform on Backdrop?

**Comment by herbdool** [comment]
I tested an upgrade on a fresh D7 site with the latest version of Webform to the latest Backdrop with latest Webform. I didn't get the same errors.

**Comment by larsdesigns** [comment]
@herbdool The version of webform module is 1.x-1.6.2 on backdropcms 1.9.5. The version of Drupal's webform is: 7.x-3.27.

**Comment by herbdool** [comment]
@larsdesigns make sure you've first updated Drupal's webform to 7.x-4.16. The latest on Backdrop is 1.x-4.16.1. Please open up a new issue if you still have problems.
