### ISSUE TITLE
Links to "Token module" point to Drupal project page

### ISSUE THREAD

**Issue by PaulHoza** [backdrop-contrib/webform#11]
In the description text for "Token values" while setting up Webform components (./webform/components/new/..), if the site doesn't have the Token module installed, the description says to install it, but the link goes to the drupal.org Token project page:

"A full listing of tokens may be listed here by installing the Token module."

These links should all point to the Backdrop version.

**Comment by herbdool** [comment]
Since tokens is now in core this message can be removed and just have a link to display tokens.
