### ISSUE TITLE
Clarify "Use Reply-To header" setting

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/webform#110]
In the Webform settings on the page `admin/config/content/webform` you can enable the option "Use Reply-To header". The setting has the following help text:

`Sends all e-mail from the domain of the default address above and sets the "Reply-To" header to the actual sender. Helps prevent e-mail from being flagged as spam.`

When I *enable* the option, there is no "Reply-To" in the e-mail header at all. When I *disable* the option, I see the "Reply-To" (i.e. the value of the webform component email, configured in an individual webform) in the e-mail header. Sounds like the contrary of what's explained in the help text.

Additionally, in both cases, the e-mail is sent from the domain, even if I choose to use a custom value in the individual webform e-mail configuration. I'm not sure if this is the intended behaviour.

Can anyone confirm my observations?

**Comment by herbdool** [comment]
When I get a chance I can check. Have you compared it to the Drupal 7 version? Wondering if it's just a possible bug in this one

**Comment by olafgrabienski** [comment]
@herbdool Haven't compared with the D7 version so far, good point, will do it and report then.

**Comment by olafgrabienski** [comment]
@herbdool I've tested Webform 7.x-4.17 now, and there it works as expected:

When the "Use Reply-To header" option is enabled (which actually is the default), the email is sent from the default address described in the help text, and I see the Reply-To value in the header. Otherwise, the mail is sent from the actual sender (email value of the form) and without Reply-To.

So, something in the Backdrop version seems to be wrong.

**Comment by herbdool** [comment]
Oddly, I don't see a difference when toggling that option: I see the Reply-To header whether it's on or off. I tested with two different Backdrop sites and the same result.

I don't know if this is because of how Gmail works.

Looking at the code I don't seen anything odd. It says that the Reply-To header is set if that checkbox is TRUE (so far so good) and if the Reply-To header doesn't already exist.

I might have to mark this as cannot replicate.

**Comment by olafgrabienski** [comment]
Thanks for trying to replicate the issue! I'll test it again and will try to report more detailed under which circumstances the Reply-To header isn't set on my Backdrop site.
