### ISSUE TITLE
Call to deprecated function format_username().

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/webform#114]
Error: Call to undefined function format_username() in webform_tokens() (line 145 of ......./modules/webform/webform.tokens.inc).

**Comment by Graham-72** [comment]
I have found in our APIs the page https://api.backdropcms.org/change-records/formatusername-changed-userformatname, so it should be function user_format_name().

**Comment by herbdool** [comment]
Seems like a pretty simple fix https://github.com/backdrop-contrib/webform/pull/115. Do you want to give it a spin @Graham-72?

**Comment by jlfranklin** [comment]
That shouldn't have caused an error.  There is a copy of the function in `core/includes/drupal.inc` for backwards compatibility.

**Comment by Graham-72** [comment]
Yes, unless you have this turned off in settings.php, which I had.

> You may disable it if all the modules you're running were built for Backdrop.
`$settings['backdrop_drupal_compatibility'] = FALSE;`
