### ISSUE TITLE
Improve design of progress bar

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#122]
The progress bar is barely visible and could use a redesign to make it look better on Backdrop, especially now that Basis is a nice clean, modern core theme. Currently:

![screenshot from 2018-10-26 14-21-45](https://user-images.githubusercontent.com/1071483/47585165-7f284700-d92a-11e8-86aa-0dc9664ba29a.png)

**Comment by herbdool** [comment]
My atttempt at a redesign:

![screenshot from 2018-10-26 14-50-19](https://user-images.githubusercontent.com/1071483/47586548-8bae9e80-d92e-11e8-9098-704b0f8e088f.png)

Inspired by https://codepen.io/oliverturner/pen/fwpaF

**Comment by herbdool** [comment]
@laryn would you have a chance to review this?

**Comment by laryn** [comment]
@herbdool I like it.

**Comment by laryn** [comment]
Slightly longer version: I've patched locally with the minor CSS updates and it works nicely. The visual effect is that it feels more modern and updated so I'd give it two thumbs up from my end.

**Comment by herbdool** [comment]
@laryn thanks for testing! I'm going to merge it then. With the last update all webforms have the progress bar visible by default so it's good to make this look better.
