### ISSUE TITLE
Cannot add submission data to a view

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/webform#130]
In the Views UI I can successfully add 'Views submission data : All values' but the option 'Views submission data: Value' to enter just one item is not working. It adds a field which cannot be configured or removed.

Similarly, if I add 'Webform submissions: Data' as a relationship I cannot configure or remove it.

**Comment by herbdool** [comment]
@Graham-72 what version of PHP are you using?

**Comment by Graham-72** [comment]
7.1.26

**Comment by herbdool** [comment]
@Graham-72 and what do you see in your watchdog logs?

**Comment by herbdool** [comment]
There was one fatal error that I saw cropping up, it only killed the ajax call thus it failed silently. @Graham-72 can you test this change. In `views/webform.views.inc`, in function `_webform_views_options_form`, change `views_ui_build_form_url` to `views_ui_build_form_path`.

I don't know if that'll fix all the issues you noticed so please test and given me full feedback, including exact error logs.

**Comment by Graham-72** [comment]
@herbdool with the change you suggest I can now build a view that includes the individual data values from the webform, thank you.

However, during building the view I am now getting a notice and a warning:
`Notice: Trying to get property of non-object in webform_component_list() (line 1052 of xxxxx/modules/webform/includes/webform.components.inc).`
`Warning: Invalid argument supplied for foreach() in webform_component_list() (line 1055 of xxxxx/modules/webform/includes/webform.components.inc).`

This seems to be happening when I start to add a field of type 'Webform submission data: Value' but before I enter the value of the webform node in the UI field 'Webform node'.

**Comment by herbdool** [comment]
Thanks @Graham-72. I've compared to a D7 site and those last warnings you see also exist there. So I think those should be captured in a separate issue.

**Comment by herbdool** [comment]
Since the latter issue also exists in D7 I've added an issue there first: https://www.drupal.org/project/webform/issues/3028948
