### ISSUE TITLE
Adding a file component breaks the drop-down menu, error in console

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#136]
I haven't figured out why yet, but when I add a file component to my webform, my drop-down menu looks like:
<img width="819" alt="screen shot 2019-03-07 at 10 26 58 pm" src="https://user-images.githubusercontent.com/397895/54011659-2c586a80-4128-11e9-9809-02b62762b183.png">

Instead of like:
<img width="901" alt="screen shot 2019-03-07 at 10 27 23 pm" src="https://user-images.githubusercontent.com/397895/54011665-31b5b500-4128-11e9-9e7e-731a0f813a75.png">

In the console I see the error `TypeError: $(...).backdropSetSummary is not a function`

**Comment by jenlampton** [comment]
Okay, so it loos like the function `backdropSetSummary()` is part of file module, and just needs to be included for the webform component when the manage file element is in use. I'm not sure why it wasn't there in the first place, but the provided PR fixes it.

**Comment by herbdool** [comment]
Nice catch! I can deal with this soon.
