### ISSUE TITLE
Fatal error with Node Clone and a Webform available as a block

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform#138]
Trying to clone a webform that is available as a block gives this fatal error:

> Error: Call to undefined function block_flush_caches() in webform_node_insert() (line 1529 of /path/modules/webform/webform.module).

At a glance the webform appears to have been cloned successfully despite the error.

**Comment by herbdool** [comment]
@laryn thanks! I suspect that we can just remove them entirely. I can't think of an equivalent for layouts - I don't know if a list of blocks for layouts is cached anywhere. Can you test? I suggest cloning and then see if the new webform is available right away in a layout.

**Comment by laryn** [comment]
@herbdool Yes, test seems okay. RTBC.
