### ISSUE TITLE
Webforms overview: Show empty text when no webforms have been created yet

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/webform#143]
`/admin/content/webform`:

<img width="860" alt="Screen Shot 2019-04-11 at 4 50 10 am" src="https://user-images.githubusercontent.com/2423362/55906582-f2432280-5c17-11e9-874c-01fc8441afa6.png">

I have tried defining `'empty' => t('No webforms created yet.')` in the `theme_table()` function returned by `theme_webform_admin_content()` in `webform.admin.inc`, only to realize that that page is now generated by a view in Backdrop 😅. We should update the "Webforms" view to show an empty table, with a "No webforms created yet." message.

**Comment by klonos** [comment]
...got myself into a "rabbit hole" of related issues in d.org 😓 😅:

https://www.drupal.org/project/views/issues/1118814
https://www.drupal.org/project/views/issues/1217394

**Comment by klonos** [comment]
...editing the "Webforms" view and enabling the "Show the empty text in the table" option (in the table format settings), shows the table header, but no text:

<img width="1198" alt="Screen Shot 2019-04-11 at 6 05 21 am" src="https://user-images.githubusercontent.com/2423362/55909654-f07d5d00-5c1f-11e9-8318-a3f51b4fa0df.png">

I have noticed the following, and have respective questions:

- The `webform_admin_content()` function has this comment: `Determine whether views or hard-coded tables should be used for the webforms table.`. Is this to account for when the "Webforms" (webform_webforms) view is disabled?

- The above function checks for `!webform_variable_get('webform_table')`, but I see no such respective setting in `/admin/config/content/webform`. Was this perhaps a setting in Webform 7.x that we have removed in the Backdrop version of the module? If so, then cleanup is needed.

**Comment by herbdool** [comment]
That config variable is listed here https://github.com/backdrop-contrib/webform/blob/1.x-4.x/config/webform.settings.json. I'm not sure about your other questions

**Comment by klonos** [comment]
OK, here's a PR to fix all this: #205

Out of the box, you get this (provided by Views):
![image](https://user-images.githubusercontent.com/2423362/188208927-389e29f9-ac03-4da3-a751-4b9c5042919b.png)

If the default view that provides the Webforms listing (machine name: `webform_webforms`) happens to get disabled, things fall back to a hard-coded table (provided by `theme_webform_admin_content()`):

![image](https://user-images.githubusercontent.com/2423362/188207857-25a737a1-1196-4475-a58f-067c2b8c6329.png)

I've moved the "There are currently no webforms on your site. ..." text out of `theme_webform_admin_content()` and into a new helper function `_webform_admin_empty_text()`, so that it can be reused by both the view and the hard-coded table.

The empty message could not have been added to `config/views.view.webform_webforms.json` as a global text area, as these do not support "dynamic" text to be added (and the second "Create piece of content." part does get generated dynamically, based on how many content types have been webform-enabled - see `webform_admin_type_list()`). I am instead adding that text to the view programmatically, during runtime, via `view::set_item()`.

To test:
1. apply the changes of the PR in a fresh installation of Backdrop with Webform enabled (and with no webforms created yet)
2. visit `admin/content/webform` -> confirm that the empty text is shown
3. disable the Webforms view (`webform_webforms`) from `admin/structure/views`
4. visit `admin/content/webform` again -> confirm that the empty text is still shown
5. add a webform or more
6. visit `admin/content/webform` again -> confirm that the table is rendered as expected
7. re-enable the Webforms view (`webform_webforms`) in `admin/structure/views`
8. visit `admin/content/webform` again -> confirm that the table is rendered as expected with Views

Bonus: I've also changed the page title of the webform listing page from "Webforms" to "Manage webforms", to match the rest of the items in the tabs (not shown in the screenshots above).

While at it, I've also made the hard-coded table generated by `theme_webform_admin_content()` more closely match the columns/style of the Views-provided listing, so there is no "reduced" UX when switching to that. Before:

![image](https://user-images.githubusercontent.com/2423362/188210928-976e6ab8-e568-4e27-9f1e-6c938318af96.png)

After:
![image](https://user-images.githubusercontent.com/2423362/188245914-f042fefb-77cc-454f-a08c-c0dd819b6fc7.png)

Specifically:
- added the "Created" and "Status" columns that were missing
- fixed an issue with `db_select()` fetching `stdClass` instead of `Node` objects, causing `node_access()` to always return false, which in turn caused the "Edit" and "Components" operations to not be shown (not even for user1) - see the "before screenshot"
- converted the links in the "View" and "Operations" columns to dropbuttons
- added the empty message as a proper parameter in the returned `theme_table()` in `webform_admin_content()` (instead of an "extra" row that was previously being conditionally added to the table, with `colspan`s etc.)
- added header sorting to the table (for all columns besides the "View" and "Operations")
- added a pager to the table, with a limit of 25 items  - same as the view (not that it would be very common to have sites with that many webforms, but you never know)

**Comment by herbdool** [comment]
Thanks @klonos! I made small tweaks and merged.
