### ISSUE TITLE
Updating from 1.2.1 to 1.2.2 I have got a warning

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/webform#15]
Updating from 1.2.1 to 1.2.2 I have got not 6 warnings it was before but only one warning - with Webform:

![webform](https://cloud.githubusercontent.com/assets/13515302/10084449/33494dda-630c-11e5-8318-9bc692c0bea4.gif)

**Comment by herbdool** [comment]
I believe I've fixed this. With an upgrade from Drupal's webform it was reporting the wrong last removed update. So as long as you had upgraded webform to 7.x-4.x then it should work now.
