### ISSUE TITLE
Label display option for "above" not working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/webform#152]
If I select "above" for the label display on a field, it is not working. It displays as "inline." 

The "none" option works, but for either a selection of "above" or "inline" the display will be "inline."

Form fields look much better with the label "above," because then the input fields all line up nicely. 

![Edit_component__First_Name___Videos](https://user-images.githubusercontent.com/3144571/67640156-4e287c80-f8c6-11e9-9162-62ee0fe9a9e4.png)

![Contact_Triplo___Videos](https://user-images.githubusercontent.com/3144571/67640168-6e583b80-f8c6-11e9-8a13-502b0f1338c7.png)

Steps to reproduce:
1) Create a new webform
2) Add a text field
3) Notice that the default position for the label is set to "above"
4) View webform to see the problem

NOTE: Changing the label position to something else and changing it back does not improve the situation. 

Possible related issues:
https://www.drupal.org/project/webform/issues/2179599

**Comment by stpaultim** [comment]
OK, based upon the feedback from @quicksketch in this Drupal issue https://www.drupal.org/project/webform/issues/2179599, I simply changed the theme to Bartik and the "above" label worked as expected. 

It would appear that something in Basis is overriding the CSS for Webform. 

Is this a Basis problem OR does the CSS for Webform need to be more flexible/resilient?

**Comment by stpaultim** [comment]
I've done a bit more troubleshooting and found something I don't understand. 

When using the Bartik theme, the following css file (/core/modules/system/css/system.theme.css) is being loaded and applying:

label {
    display: block;
    font-weight: bold;
}

This is NOT happening with Basis. I don't understand why this CSS is only be loaded in Bartik and not Basis?

I'm not sure that I can submit a Pull Request to help fix this without understanding this problem.

**Comment by stpaultim** [comment]
OK, I see that Basis is excluding that css file:

```
; Remove unwanted core CSS
stylesheets[all][] = system.theme.css
```
So, in summary, I now understand that Webform is relying on the core css to apply a display: block; property to label, but Basis does not load that CSS file. 

What is the best way to fix this?

Is this a bug with Basis and we need to add that property to labels OR should webform include the necessary css?

Checking first to see if we should fix this in core: https://github.com/backdrop/backdrop-issues/issues/4165

**Comment by herbdool** [comment]
From Webform's point of view it seems like we can't rely on `system.theme.css` being present so we may need to add the css in the module.

**Comment by stpaultim** [comment]
I'm coming to that conclusion as well. But, there is a part of me that thinks of this as a bug in core (Basis). On the other hand, it's a simple enough change and if Basis can override that file so might another theme. 

I went ahead and created a PR for webform, but could be convinced to make the PR for Basis instead.

https://github.com/backdrop-contrib/webform/pull/153

**Comment by stpaultim** [comment]
@herbdool - Thanks for finishing this. Sorry, I didn't get back and complete the job.
