### ISSUE TITLE
Select options using radio buttons not available.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/webform#16]
I would like to have a field that is entered by means of radio buttons. There seems to be an issue here which I will investigate.

**Comment by earthday47** [comment]
I am also seeing this behavior

**Comment by earthday47** [comment]
I believe it is because `theme_checkboxes()` has been removed from core.

https://github.com/backdrop/backdrop/pull/324

Webform will need to be patched in `components/select.inc` so that instead of calling theme_checkboxes is uses the new `container` method.

**Comment by earthday47** [comment]
pr for issue ^^
