### ISSUE TITLE
Additional field types from contributed modules not showing up in field type list

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/webform#160]
I have a few modules installed on a site that create additional field types (telephone, entity reference, etc), and none are showing up in the list of available field types for webforms. Was curious if this was expected behavior, and if so, I would like to make some feature requests; if not expected, then i would consider this a bug.

Working with Backdrop 1.15.2.

**Comment by kelizoliva** [comment]
I reviewed admin/config/content/webform and the field types from contributed modules are not listed there either.

**Comment by herbdool** [comment]
I cannot replicate.

![Screenshot from 2020-05-11 10-43-36](https://user-images.githubusercontent.com/1071483/81575050-9267ff80-9374-11ea-9c68-b96245df3ff2.png)

I enabled most recent Backdrop core 1.x, webform 1.x-4.x, recent entity reference module and went to `admin/structure/types/manage/webform/fields`. From the screenshot above you can see that I was able to create an entity ref field.

These field types are associated with the content type (webform as a content type) and not available as fields for the webform as a form. I'm not sure if that's where you're getting stuck but wanted to clarify this in case anyone reading this is getting confused.

**Comment by kelizoliva** [comment]
Yes, I meant webform as a form. The content types are fine.

**Comment by herbdool** [comment]
I see. So field types are not available to webform unless the module explicitly says that they also built in that functionality. In webform they're called components.

If you want to make a reference in a webform, you can use https://github.com/backdrop-contrib/webform_references. As for telephone you may have to search Drupal 7 webform solutions for that. I don't know what works. Perhaps a custom validation.
