### ISSUE TITLE
Duplicate form classes

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform#165]
I'm debugging something and happened to see that form classes are duplicating:

![Screen Shot 2020-09-14 at 10 22 16 AM](https://user-images.githubusercontent.com/871421/93105229-6e932e00-f674-11ea-9839-91b7207b7c21.jpg)

**Comment by laryn** [comment]
Not sure if this is the best way, but here's a PR:
https://github.com/backdrop-contrib/webform/pull/166

**Comment by herbdool** [comment]
@laryn odd. Do we see this in D7 as well?

**Comment by laryn** [comment]
You know, I should have checked on another site because I don't see it on another Backdrop site... I'll close this for now and assume it's not the webform module but probably another module or customization that's causing it. I will reopen if I get more specifics.
