### ISSUE TITLE
Data-Migration from Webform 7.x-4.12 (Drupal) does not work

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/webform#17]
Migration from Drupal 7.41 to Backdrop 1.3.2, webform was not uninstalled in order to keep the data.
Webforms do not show and following errors:
Warning: array_flip() expects parameter 1 to be array, null given in webform_components() (Zeile 4323 von /home/www/backdrop/modules/webform/webform.module).
and then many times (seems to be one for every webform):
Warning: array_key_exists() expects parameter 2 to be array, null given in webform_components() (Zeile 4328 von /home/www/backdrop/modules/webform/webform.module).
and last:
Warning: Invalid argument supplied for foreach() in form_type_checkboxes_value() (Zeile 2400 von /home/www/backdrop/core/includes/form.inc).

**Comment by herbdool** [comment]
I have the same issues. I can submit a pull request to fix some of this.

Issue one: the View: webform_webforms probably doesn't exist and webform_table probably set to "null" in the config. So manually set that to 1 to default to the table as a quick fix, or import the webform_webforms from some other site. (see function webform_admin_content() under includes/webform.admin.inc)

Issue two: the webform settings aren't saving properly so nothing appears for options to add fields. Under function webform_admin_settings_submit() in includes/webform.admin.inc move this snippet so it's just before the closing bracket:

```
  $config = config('webform.settings');
  foreach ($form_state['values'] as $key => $value) {
    $config->set($key, $value);
  }
  $config->save();
  backdrop_set_message(t('The configuration options have been saved.'));
```

For some reason it was at the beginning so it missed all the changes before saving.

Issue three: the webform_disabled_compenents needs to exist in the config as an empty array at first. So do this manually to get it working in webform.settings.json add this somewhere in the middle:

```
"webform_disabled_components": [],
```

There also needs to be a patch to ensure these variables exist in the .install for anyone else trying to install.

That should get it working, more or less. I'm still trying to squash one warning in the meanwhile:

`Warning: array_flip() expects parameter 1 to be array, null given in /home/nubeli/a.nubeli.org/backdrop/core/includes/common.inc on line 1739`

**Comment by herbdool** [comment]
The last issue I mentioned is fixed by adding the following to the webform.settings.json config:

```
    "webform_allowed_tags": [
        "a",
        "em",
        "strong",
        "code",
        "img"
    ],
```

So most of these issues are just from the module not providing defaults when upgrading instead of doing a fresh install. And one mistake in the settings submission form.

Hopefully that at least gets it working.
