### ISSUE TITLE
Field suffix and prefix should look better in Basis (and most themes)

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#176]
We can set some defaults for the field prefix and suffix so they look better in most themes. Basis is making them display: block; which doesn't look good.

**Comment by herbdool** [comment]
@jenlampton @laryn wondering what you think - simple fix I think.

**Comment by stpaultim** [comment]
Reminds me of this issue:
https://github.com/backdrop-contrib/webform/issues/152

**Comment by herbdool** [comment]
Yeah, there are some similarities. Some good defaults here means it'll work for most themes.

**Comment by laryn** [comment]
Makes sense to me.

**Comment by herbdool** [comment]
Thx!

**Comment by jenlampton** [comment]
Love it! Nice work :)
