### ISSUE TITLE
Submission information not visible when viewing or editing submission.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#179]
Viewing:
<img width="1193" alt="Screen Shot 2021-03-02 at 5 07 29 PM" src="https://user-images.githubusercontent.com/397895/109736805-cf0e1d00-7b79-11eb-8c8f-d9e86da40902.png">

Editing:
<img width="1177" alt="Screen Shot 2021-03-02 at 5 07 52 PM" src="https://user-images.githubusercontent.com/397895/109736841-dd5c3900-7b79-11eb-9b1b-2b60d5ce6ce3.png">

The problem is some CSS on the fieldset:
```
.webform-submission-info-text {
    overflow: hidden;
}
```
Removing this fixes the problem
<img width="1211" alt="Screen Shot 2021-03-02 at 5 08 58 PM" src="https://user-images.githubusercontent.com/397895/109736919-0381d900-7b7a-11eb-8703-0ff8c0212e0d.png">

**Comment by laryn** [comment]
WFM

**Comment by herbdool** [comment]
Thanks @jenlampton!
