### ISSUE TITLE
Add link component to Webform

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/webform#187]
While Backdrop has lot's of field types as shown on the screenshot:

![Screen Shot 2021-10-13 at 8 22 12 PM](https://user-images.githubusercontent.com/56604405/137237204-ccdb16b2-3b6f-45af-95c5-b9c073cf7017.png)

Webform currently offers the following field types only:

![Screen Shot 2021-10-13 at 8 55 01 PM](https://user-images.githubusercontent.com/56604405/137237402-4ec7f951-4bd6-4600-9545-4edfa4ae03d9.png)

There is a module https://www.drupal.org/project/webform_link for Drupal 7, Drupal 8/9 support support links in core, so Backdrop version of Webforms is lacking a field type for links.

Thanks for consideration!

**Comment by herbdool** [comment]
A link field might be straightforward enough to put into webform core. @alanmels are you interested in providing a PR?

**Comment by alanmels** [comment]
Unfortunately, no time for that.

**Comment by herbdool** [comment]
It turned out to be pretty easy to incorporate webform_link into core. https://github.com/backdrop-contrib/webform/pull/193

@alanmels care to test? I improved on it a bit by using the html5 url input type (similar to the email input type) plus added placeholder, disable options (all copied from email).

**Comment by alanmels** [comment]
@herbdool, thank you very much for getting the link field into webforms. Unfortunately, these days I am super busy, but in about two weeks I will run some tests.

**Comment by alanmels** [comment]
I quickly test this and while a link type of filed is added successfully, unfortunately UI displays only it's label. Viewing the source only gives:

```
<div class="form-item webform-component webform-component-link webform-component--link">
  <label>Link </label>
 
</div>
```

So the link field itself doesn't get rendered at all.

**Comment by herbdool** [comment]
I'll need more details. For me when I view the webform the form field is rendered like:
![Screenshot from 2021-10-22 17-11-50](https://user-images.githubusercontent.com/1071483/138523511-2ab790b3-31b1-4f84-8654-25d03fed8ad4.png)

And a webform result displays like:

![Screenshot from 2021-10-22 17-13-17](https://user-images.githubusercontent.com/1071483/138523595-2db58008-46dd-4886-8804-461060ffb1e9.png)

And when downloading it's plain text. I had tweaked the result display but that html doesn't match what you pasted above.
