### ISSUE TITLE
Array to string conversion in webform-analysis-component.tpl.php

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/webform#188]
The template file that produces the output for webform's  Results > Analysis currently throws php notices for Array to string conversions in line 17, when trying to print the variable $classes.

This happens because Backdrop, unlike Drupal, passes the variable $classes as an array, which must be flattened within the template file. See [this document](https://docs.backdropcms.org/change-records/removed-theme-process-layer) that explains this change (basically they removed the theme process layer in Backdrop, which used to take care of flattening this array before passing it to the theme template).  

The solution is simple:  replace line 17 with `print implode(' ', $classes);`, which is what other templates use nowadays (e.g. node.tpl.php).

**Comment by herbdool** [comment]
Fixed.
