### ISSUE TITLE
[UX] Provide hints that in order to have attachments allowed, you need to enable "HTML mail system"

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/webform#203]
This was triggered by this discussion in Zulip:

@keiserjb 
>Say you make a webform so anybody can upload documents but then the people getting the email don't have access to view the documents in the website, and you don't want to give it to them. In Drupal 9 there is a way to send the files as attachments on the webform submission email.
>
>I've been trying to make this work with Rules in Drupal 7 and Backdrop but haven't been successful. https://www.drupal.org/project/webform_rules

@laryn 
> @keiserjb Look at the "Webform > Emails" page. Under the email template portion you should see a checkbox to " Include files as attachments "

@keiserjb 
>in Backdrop? I don't see that.

@laryn 
> Yes, in Backdrop. Hmmm... is your system set to allow HTML mail -- just a guess. (In `admin/config/content/webform` look for "HTML mail system" checkbox)

@keiserjb 
>thank you @Laryn did not know that was there
>
>oh my goodness that is so much easier than what I was trying to do
>
>and it's easier than it was in Drupal too

...

@keiserjb 
>It's weird that when I Googled how to do that I got some convoluted solution with Rules.

@laryn 
>Maybe from before that option was added?

I think that we can do a better job at making this feature more discoverable, so that people don't go around in circles to achieve such a common thing as attaching files in the webform email.

**Comment by klonos** [comment]
PR available for review here: #204

Instead of completely hiding the checkbox with `#access`, it is using `#disabled`:
![image](https://user-images.githubusercontent.com/2423362/188127240-370f3ac6-b21c-4136-9992-121c8477e57a.png)

...so people see the option, but cannot enable it -> then they read the help text, which tells them what needs to be done where + also provides a link to that page -> UX+ 😉

**Comment by keiserjb** [comment]
This seems much improved.
