### ISSUE TITLE
Labels strip out HTML but help text says certain tags are allowed

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/webform#206]
**Steps to reproduce**

1. Create a webform
2. Add a select options component
3. Attempt to customise the label with HTML (try adding a font awesome icon if you have the module installed e.g. `<i class="fas fa-lightbulb"></i>` or adding some formatting to the label `<b>Choose</b> this`) using one of the allowed tags listed below

**Expected result**
HTML is applied on the form

**Actual result**
HTML is stripped from the form but remains in the edit screen.
![image](https://user-images.githubusercontent.com/20357797/190115531-e48bb1ab-74f2-4e72-9869-20b76d6dea11.png)
![image](https://user-images.githubusercontent.com/20357797/190116028-aa0e1fc0-9b29-419b-9614-7cddb8e5ec22.png)

**Comment by yorkshire-pudding** [comment]
I've worked out that `webform.settings.json` has the following line:

```json
    "webform_allowed_tags": [
        "a",
        "em",
        "strong",
        "code",
        "img"
    ],
```

However this doesn't cover all the tags from the list described in help text under the component.

I suggest there are 2 options to fix:

1. Add all the listed html tags to `webform_allowed_tags`
2. Expose this setting in the admin config and populate the help text with the allowed tags.  In theory this could use the same UI as the text filter config, but the config for both is stored differently so it would not be a straight copy of the pattern.  For example, in my `filter.format.full_html.json`, it says:

```json
        "filter_html": {
            "status": 0,
            "weight": -10,
            "settings": {
                "allowed_html": "<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h3> <h4> <h5> <p> <img> <figure> <figcaption>"
            },
            "module": "filter"
        }
```

Option 1 would be easiest and I could easily [add a PR to cover this](https://github.com/backdrop-contrib/webform/pull/207).  However, it may be best to allow site admins to restrict what HTML tags can be used by those creating webforms, which would require Option 2, which is a more complex change.

**Comment by herbdool** [comment]
@yorkshire-pudding thanks for bringing this up. I'm curious how this behaves in core currently. Are you able to add more HTML there in select lists?

**Comment by yorkshire-pudding** [comment]
Hi @herbdool - this is where they are added in core:
Configuration > Content authoring > Text Editors and formats

Let's say we look at Filtered HTML, we see this option (Limit allowed HTML tags)

![image](https://user-images.githubusercontent.com/20357797/220155765-4a19f389-272b-41f3-bf55-59c0bc4cb2aa.png)

For ease, I'm using one on a site I'm building at the moment and it has a couple of extra ones in.
The list of tags can be edited here with a space separated list of tags.

![image](https://user-images.githubusercontent.com/20357797/220155464-3891c1af-1f73-4a4f-9df7-54a6e51bbdbc.png)

**Comment by herbdool** [comment]
Tricky issue. The `webform_allowed_tags` is a list of HTML tags for a bunch of webform components and labels of those components. It might be worthwhile exposing that in the webform settings form regardless. But we probably do not want to allow all the same tags as core's: `_field_filter_xss_display_allowed_tags()` which is where the option element textarea is getting that text. So maybe just have the text description overwritten.

**Comment by yorkshire-pudding** [comment]
I agree that there is a limited number of html tags that are needed.  My needs were quite simple and just so I could display font awesome icons against each option.

**Comment by yorkshire-pudding** [comment]
Whatever we do, the help text should be perhaps drawn from the same list so user expectations are managed.

**Comment by herbdool** [comment]
@yorkshire-pudding I've got this PR to make it easier to edit the list: https://github.com/backdrop-contrib/webform/pull/219. I didn't see any easy way to change the help text. Core passes the list of tags to JS and we'd need to be able to alter that. I didn't want to spend more time on that part.

**Comment by yorkshire-pudding** [comment]
Thanks - I should be able to test this tomorrow.

**Comment by yorkshire-pudding** [comment]
Thanks @herbdool - I've tested this and it works well. I've left an optional suggestion for clarifying the description.
