### ISSUE TITLE
Views: #dependency to #states

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#210]
In webform_handler_field_submission_data.inc. `#dependency` no longer works for Views, need to use `#states` instead.

**Comment by argiepiano** [comment]
LGTM! Question: why are you using `*=` in the jquery selector? Are there any chances that there will be other input fields that contain parts of the name `options[custom_label]` ?  why not just `=`?

**Comment by herbdool** [comment]
No good reason - I had copied it from another module. I think I'll remove it.
