### ISSUE TITLE
Cannot add conditionals when using PHP8

### ISSUE THREAD

**Issue by Rich-DR** [backdrop-contrib/webform#212]
Problem: the 'Add a new condition' does not show the fields that can be added. PHP error message is: 

Undefined index: source_type in webform_conditional_element_remove() (line 811 of ..../modules/webform/includes/webform.conditionals.inc). 

This is on a fresh Backdrop1.23.1 installation with MySQL5.5/PHP8.0.27  Changing to PHP7.4.33 solves the problem.

**Comment by herbdool** [comment]
I think some of this may be addressed once I merge in https://github.com/backdrop-contrib/webform/issues/213

**Comment by herbdool** [comment]
@Rich-DR would you be able to test https://github.com/backdrop-contrib/webform/pull/214 to see if that fixes your bug?

**Comment by Rich-DR** [comment]
@herbdool I confirm that, yes, changing the code at https://github.com/backdrop-contrib/webform/pull/214 code in includes/webform.conditionals.inc fixes the conditionals bug (I'm a novice and don't know how to easily apply the whole suite of changes in those other files)

**Comment by yorkshire-pudding** [comment]
@Rich-DR - this has now been merged and is in the latest release.

I've tested this in the new released version and it now works well on PHP 8.1. Closing
