### ISSUE TITLE
Warning: Attempt to read property "is_draft" on bool 

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform#217]
> Warning: Attempt to read property "is_draft" on bool in webform_client_form() (line 2703 of /var/www/html/web/modules/contrib/webform/webform.module).

PR coming.

**Comment by laryn** [comment]
@herbdool and @quicksketch I'm not as familiar with webform code but this makes sense to me, see what you think of the PR.

**Comment by herbdool** [comment]
Interesting. I wouldn't have thought a submission could be a boolean. Is there a bug somewhere else? I'm wondering if this would just paper over something else.

@laryn I see a commit on your fork but not a PR.

**Comment by laryn** [comment]
Thanks @herbdool I just made it into an actual PR. I'm still trying to figure where this comes from but I think it may be in custom code so not necessarily a bug per se. But since `$submission` defaults to bool (`FALSE`) in the function itself maybe good to be defensive here?

**Comment by herbdool** [comment]
Thanks @laryn! I hadn't noticed that it could be FALSE so that makes sense.
