### ISSUE TITLE
If webform_table default defaults to false then the upgrade needs to check for webform_webforms view

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#22]
Upgrading from Drupal with webform and there's no check to see if the default views exist and install them if they don't.

**Comment by herbdool** [comment]
As a stopgap, I thought I'd just import the view but just realized there doesn't seem to be any way to import views in Backdrop. This functionality was removed? I'm guessing the new way would be to convert the export into a config format and import that, no?

**Comment by jenlampton** [comment]
>  This functionality was removed?

No, the "import a thing" functionality was added for everything else, so the UI is now consolidated and located at `admin/config/development/configuration/single`.  You'll need the JSON output from backdrop though, not the PHP output from Drupal.

**Comment by herbdool** [comment]
Fixed in 1.1.3
