### ISSUE TITLE
import webform results data?

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/webform#225]
Is it possible to import webform results data here as it is in D8?

**Comment by argiepiano** [comment]
There is a D8 module, [Webform Submission Import](https://www.drupal.org/project/webform_submission_import) - is that like what you are looking for? It's a simple module. It shouldn't be hard to create a similar one in Backdrop, but as far as I know, something like that doesn't exist... yet.

**Comment by leeksoup** [comment]
@argiepiano - Thanks! "Submission export/import" is a listed standard feature of Webform in D8/9/10. It's on the main project page, and I have used it in the past. 

I can still look at the standalone module code that you linked, though, especially since you say it's simple.

**Comment by leeksoup** [comment]
@argiepiano - Hmm, I just took a look, and it may be simple to you, but not that simple to me. :) 

Will it work to run it through the module converter, or does that only work for D7 modules?

I am considering just exporting/ importing the submission results table via SQL ... I know I have to also sync the "next submission number" field but can do that via UI. Bad idea??

**Comment by argiepiano** [comment]
I think I spoke to soon! The module can't be run through coder update because it is D8.

**Comment by laryn** [comment]
Try https://github.com/backdrop-contrib/webform_import

**Comment by leeksoup** [comment]
@laryn - I'm having problems with about half the fields not importing correctly. Seems to be a mismatch between the exported column headers and the ones the import is looking for. Reported at https://github.com/backdrop-contrib/webform_import/issues/4

**Comment by laryn** [comment]
@leeksoup Thanks, I responded there. I think it's a good idea to get these import defaults all matching webform export defaults.
