### ISSUE TITLE
Warning: Trying to access array offset on value of type null in _webform_csv_data_file()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/webform#231]
Downloading results of a webform where in any submission, an optional file component is not populated, gives the following warning:

Warning: Trying to access array offset on value of type null in _webform_csv_data_file() (line 574 of /mysite/modules/contrib/webform/components/file.inc).

There is a warning issued for each submission with empty file component, so there can be a lot of warnings (on-screen if errors are turned on, in the dblog even if not).

To reproduce the error,

* Create a webform containing a file component but don't make it required.
* Submit the form with no file in the field.
* Download the results using the default download settings.

**Comment by herbdool** [comment]
Thanks @bugfolder!

Only just saw the PR. Feel free to ping me when creating a PR.
