### ISSUE TITLE
Update readme to reflect what version of webform was ported

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#26]
As far as I can tell it's 7.x-4.4 based on the subsequent commit log for [issue 2447745](https://www.drupal.org/node/2447745). There have been a lot of commits since then--they've been busy fixing bugs!--so it would also be good to track the Drupal changes and merge them in

**Comment by jenlampton** [comment]
👍

**Comment by Al-Rozhkov** [comment]
Should we create another issue to list all new commits from d.org or separate issue for each one? The list going to be huge. But it would be great to merge bug fixes with BD port of Webform.

**Comment by jenlampton** [comment]
I'd recommend starting with one huge META issue, and spliting off into other issues only as necessary.

**Comment by herbdool** [comment]
Fixed
