### ISSUE TITLE
Description - how to replace?

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/webform#29]
Hi!

To replace (move) **Description** to another place - should I edit the template?
Hm, why there is no a way to replace (move) it from admin **Edit component** ...

Thank you!

![des](https://cloud.githubusercontent.com/assets/13515302/13922005/a1d134fa-ef8b-11e5-95b5-25969ce53e06.gif)

**Comment by klonos** [comment]
Where would you like to move it?

**Comment by bd0bd** [comment]
Right now I have it underneath the field.
But sometimes I might need it like this:

![des](https://cloud.githubusercontent.com/assets/13515302/13926130/05da6042-ef9c-11e5-9890-4db6fa5d0464.gif)

Thank you!

**Comment by jenlampton** [comment]
Ah, this is not a webform problem but a backdrop core problem.  You'll need to override `theme_form_element()`.
