### ISSUE TITLE
Query topic and email options

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/webform#30]
I am trying to use the query options feature whereby the user selects a topic and webform emails the form result to a specific email address, using this admin form to set the addresses:
![deben rowing club 2016-04-04 08-11-36](https://cloud.githubusercontent.com/assets/10559274/14240570/d83792de-fa3d-11e5-94fa-512425097f97.png)
But the email addresses I enter do not seem to be being saved either in the webform.settings config file nor in a data table e.g. webform_emails.

I am now trying to work out what should be happening here.

**Comment by herbdool** [comment]
It's not clear what you're doing here @Graham-72 . What path? Which field type?

**Comment by herbdool** [comment]
Oh, I see where that screenshot is from: `/node/###/webform/emails/#`

The problem I see is that the js isn't toggling the visibility of the Component e-mail options table. But when I disable the css rule and show it by default I am able to enter emails and save. On re-edit the emails still appear so I'm confident that part is working. I'm going to open a new issue for the one I'm seeing. (I'm using 1.x-15.1 for testing this.
