### ISSUE TITLE
E-mail header details — wrong From e-mail

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/webform#36]
In the message received from the form I have this header:

From: site-admin@my-site.com — it is **wrong**!
To: site-admin@my-site.com
Reply: sender@domain.com

I the From field is displayed the admin's e-mail but I would like it be something like robot@my-site.com or a sender's e-mail (the same like in Reply field).

Can not understand how to do it :smile: 

Thank you!

**Comment by jenlampton** [comment]
> The From field is displayed the admin's e-mail but I would like it be something like robot@my-site.com or a sender's e-mail (the same like in Reply field).

You are not allowed to send an email as someone else (a sender's e-mail), that is how your site gets blocked as a spoofer (or spammer!) and you end up on a blacklist. 

The From address is the same one you specified at `admin/config/system/site-information`. Change that to `robot@my-site.com`.
