### ISSUE TITLE
webform_update_last_removed() not correctly set in current release.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#38]
It looks like `webform_update_last_removed()` contains a drupal 6 upgrade number, but if this module was ported to Backdrop from Drupal 7 this should be the number of the last Drupal 7 update hook, and should be 7000+.

The most recent update hook in webform 4.x  is numbered 7430, so I'd guess that's what should be in hook_update_last_removed() but I read https://github.com/backdrop-contrib/webform/issues/26 and now I'm not sure that's corect as the last hook in 4.4 is numbered 7421.

**Comment by jenlampton** [comment]
Ah, okay, in the repo it looks like that number has been updated to 7430.  Any chance we can get a new release? I downloaded the tarball and that's where I found the old number.

**Comment by herbdool** [comment]
Oops, I think I made a mistake in thinking it was 7430. @jenlampton you're right, it was 7421. This repo was forked somewhere between 4.4 and 4.5
