### ISSUE TITLE
Webform commits from 7.x-3.24 to 3.25

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/webform#40]
There are two of them, [one of which is a security-related one](https://www.drupal.org/node/2820444):

https://www.drupal.org/project/webform/releases/7.x-3.25

> Issue [#2600316](https://www.drupal.org/node/2600316) by torotil: Partially backport webform_get_submissions() refactoring [[view commit](http://cgit.drupalcode.org/webform/commit/?id=5acd758757e6018cd6f0bad2656604781ea156f4)]
> Issue [#2035329](https://www.drupal.org/node/2035329) by jweowu: Explicitly deny access to uploaded private files, if not permitting access. [[view commit](http://cgit.drupalcode.org/webform/commit/?id=0f7e2748e6af065da2061bf0d805e0f37831c690)]

The security commit changes seem to be in our latest 1.x-1.x (can't see a commit or PR for it though ??), so PR for the other issue upcoming...

**Comment by klonos** [comment]
> ...PR for the other issue upcoming...

Sorry, but it seems that there are some other changes in the code that conflict with the d.org commit. This is beyond my skills and free time available currently. Perhaps we need to check the previous commits first: https://github.com/backdrop-contrib/webform/issues/39

**Comment by herbdool** [comment]
@klonos it's based on 7.x-4.x, not the 7.x-3.x branch.
