### ISSUE TITLE
Admin theme

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform#41]
On a site I'm working on I notice that when editing a webform the Admin theme is respected, but on the "Webform" and "Results" tab it uses the front end theme. It seems that these should use the Admin theme as well, right?

**Comment by herbdool** [comment]
Confirmed that Webform on Drupal 7 uses admin theme for those tabs by default.

**Comment by herbdool** [comment]
@laryn this should work now with the PR just merged. There will be a new release soon.
