### ISSUE TITLE
Add me as a maintainer?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform#46]
Looks like @quicksketch has his hands full and @biolithic doesn't want to be a maintainer. I'd be willing to be one of the maintainers if that's okay with the current maintainers.

I'll mostly focus on making sure that releases from Drupal 7 get merged in and make small fixes here and there.

**Comment by quicksketch** [comment]
Hi @herbdool! That would be great! I've added you officially in https://github.com/backdrop-contrib/webform/commit/a330aa0620fe6b2555388d8c499d9e097a9512cc. As you are already a contrib member you can get started right away. Thanks!

**Comment by herbdool** [comment]
Thank you! Glad to help
