### ISSUE TITLE
$form_state key 'complete_form' changed to include underscore

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/webform#6]
https://www.drupal.org/node/1235918. This was inherited by Backdrop, but still there in Webform.
Pushing change now.

**Comment by docwilmot** [comment]
Fixed with https://github.com/backdrop-contrib/webform/commit/5872ff4eb394268999335dbfa3ddad83e9dea01d

**Comment by serundeputy** [comment]
@docwilmot I don't think you should be pushing directly to the release branch of a project.
You should file a `PR` so the community has a chance to review (RTBC) and the module's maintainer has a chance to discuss, approve or propose a different course.

https://github.com/backdrop-ops/contrib/blob/master/README.md

It is just a matter of policy and procedure.

**Comment by docwilmot** [comment]
I agree. Started this terrible practice here https://github.com/backdrop-contrib/webform/issues/2#issuecomment-127764214, and considered a PR for this but given it is 3 lines of find-and replace, thought I might as well finish what I started. Will reconsider in future.
