### ISSUE TITLE
Webform upgrade Fatal Error: Cannot use lexical variable $value as a parameter name

### ISSUE THREAD

**Issue by jjmonterey** [backdrop-contrib/webform#76]
When updating database after upgrading to latest webform release:

Fatal error: Cannot use lexical variable $value as a parameter name in /home/mydomain/public_html/modules/webform/components/select.inc on line 757

**Comment by jjmonterey** [comment]
I should add that it's php version 7.1.2 on Siteground shared hosting

**Comment by laryn** [comment]
@herbdool on Gitter:

> it might be related to this issue: https://www.drupal.org/node/2811063 Are you using PHP 7.x and Opcache?

**Comment by jjmonterey** [comment]
Reverting to PHP 7.0.x from 7.1.x fixed the issue thanks

**Comment by herbdool** [comment]
There's still a patch to apply here so I'm reopening.

**Comment by jjmonterey** [comment]
Thanks for the update.

On D.org the patch for webform/components/select.inc had:

/**
  * Implements _webform_action_set_component().
  */
 function _webform_action_set_select($component, &$element,
&$form_state, $value) {
   // Set the value as an array for multiple select or single value otherwise.
   if ($element['#type'] == 'checkboxes') {
     $checkbox_values = $element['#options'];
-    array_walk($checkbox_values, function(&$value, $key) use($value) {
-      $value = (int)(strval($key) === $value);
+    array_walk($checkbox_values, function(&$option_value, $key) use($value) {
+      $option_value = (int)(strval($key) === $value);
     });
   }
   else {
     $value = $component['extra']['multiple'] ? array($value) : $value;
   }
   $element['#value'] = $value;
   form_set_value($element, $value, $form_state);
 }

I found no comparable code to patch in Backdrop
webform/components/select.inc which surprised me.

I'm a site builder and have applied patches but have limited php
knowledge. It seems to me that the _webform_action_set_component() is
a rules action set component. Drupal has a webform rules module but
Backdrop doesn't yet have a port of this. Just curious about how this
will be resolved.

**Comment by herbdool** [comment]
I've addressed and committed the patch.
