### ISSUE TITLE
All webforms upgraded from Drupal forgot their "submission access"

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#94]
...so I'm needing to manually go and update them all after upgrade.

It looks like the `webform_roles` table is still using the Drupal 7 `rid` when Backdrop has switched to a machine name for `role` instead.

---
PR: https://github.com/backdrop-contrib/webform/pull/97

**Comment by jenlampton** [comment]
I'm going to attempt an update hook that replaces all instances of `rid` with `role` and manually replaces `1` with `anonymous` and `2` with `authenticated` to match the change from `DRUPAL_ANONYMOUS_RID` => `BACKDROP_ANONYMOUS_ROLE` and `DRUPAL_AUTHENTICATED_RID` => `BACKDROP_AUTHENTICATED_ROLE` accordingly.

**Comment by jenlampton** [comment]
I just pushed a pull request that seems to solve the issue on my site: 
https://github.com/backdrop-contrib/webform/pull/97

**Comment by herbdool** [comment]
@jenlampton thank you for the PR!
