### ISSUE TITLE
Webform content view should use Operations drop-buttons

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#95]
Views in Backdrop have a nice way to create Operations drop-buttons, check out the content or file listing for an example.

**Comment by herbdool** [comment]
@jenlampton think I just understood what you're suggesting. Turns out to be easy-peasy! Just thinking about how to deal with an update hook. I could replace the view people have currently with this one, but they might have made customizations which would be lost.

**Comment by jenlampton** [comment]
In core we check to see if the view is in a default state, and if so, we update it. If not, we leave it alone.

**Comment by herbdool** [comment]
@jenlampton Makes sense. In checking it's not clear if I should skip if storage == 4, or only apply if storage == 2. In core I saw checks for if the view is new but not if it was overridden. From what I can tell 4 means the view is in code and default, and 2 means it's overridden. When I create a totally new view it doesn't have a storage state at all.

**Comment by herbdool** [comment]
I think I figured it out (I could have just looked at the code first). I figure I'll use: `if ($config->get('storage') != VIEWS_STORAGE_OVERRIDE) {` which is the equivalent of checking for "2".

**Comment by herbdool** [comment]
Committed changes.
