### ISSUE TITLE
PHP warnings when upgrading webforms from Drupal 7

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#96]
```
Warning: array_flip() expects parameter 1 to be array, null given in webform_components() (line 4737 of backdrop/modules/contrib/webform/webform.module).
Warning: array_key_exists() expects parameter 2 to be array, null given in webform_components() (line 4742 of backdrop/modules/contrib/webform/webform.module).
Warning: array_diff_key() [function.array-diff-key]: Argument #2 is not an array in webform_components() (line 4750 of backdrop/modules/contrib/webform/webform.module).
```

PR: https://github.com/backdrop-contrib/webform/pull/104

**Comment by herbdool** [comment]
@jenlampton Is this during the upgrade or right after?

**Comment by jenlampton** [comment]
It may have been immediately after. I'm going to do the whole upgrade again in a day or two, I'll report back after :)

**Comment by jenlampton** [comment]
This happens when visiting update.php - before the updates are run. After the update completes the errors do not display anymore. It looks like we may need to add a check for if these various values are set before we use them in order to prevent this flood of errors.

I'm working on another upgrade that involves webform module, and I'm experiencing the exact same errors again.

**Comment by jenlampton** [comment]
Pushed a PR that prevents these warnings during upgrade: https://github.com/backdrop-contrib/webform/pull/104

**Comment by herbdool** [comment]
I have no objection to the PR--a good thing to check for--but I'm wondering what is it that would be trying to retrieve webform_disabled_components on update.php, even before any update hooks are run? You'd think update.php would avoid loading anything from webform. I'm going to try a quick test of the PR.

**Comment by herbdool** [comment]
I've had trouble recreating the error. I made sure that the Drupal 7 db I was upgrading didn't have the variable webform_disabled_components, not in the variable table nor in the cache_bootstrap table. So that's odd. Still I'll test the PR to ensure it doesn't cause issues.

**Comment by herbdool** [comment]
PR seems ok--I didn't get any errors on an upgrade--so I think I'll merge it.
