### ISSUE TITLE
Markup form component does not save.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/webform#99]
When configuring a webform `form components`:

* select type `markup`
* Add the component name
* click save

Expected result:
  * See and configure markup component

Actual result
  * no new component added

**Comment by herbdool** [comment]
Hi @serundeputy, I can't replicate!

I added a 1.x-1.6.1 on a fresh site; created a new webform; added a textfield then added a markup field. I set it to show on form only = that worked. Then edited it to show on form and on submission = that worked.

**Comment by herbdool** [comment]
I'm going to close unless you're able to confirm it is an issue.
